name: Mapa da Criminalidade de São Paulo
description: Uma análise dos dados da SSP de crimes no Estado de SP
url: https://rimolive.github.io/mapa-crime-sp

baseurl: /mapa-crime-sp
github: 'rimolive/mapa-crime-sp'
markdown: kramdown

exclude:
  - README.md
  - CONTRIBUTING.md

collections:
  scripts: {}
  reports: {}

defaults:
- scope:
    path: ""
  values:
    menu_template: menu.html
    menu_entry: Welcome